area = 1200

[t1] # drift and elapsed time from image k to image k+1
dt = [30, 100, 1300]
dist = [200, 250, 300]


[t2] # for small floes?
arearatio = 0.18
majaxisratio = 0.07
minaxisratio = 0.08
convexarearatio = 0.09

[t3] # for large floe?
arearatio = 0.28
majaxisratio = 0.1
minaxisratio = 0.12
convexarearatio = 0.14

[mc_thresholds]
# for matchcorr computation
mxrot = 10 # maximum rotation
psi = 0.95 # minimum psi-s normalized crosscorrelation
sz = 16 # minimum "side-length" for a floe
comp = 0.25
mm = 0.22
# For determing goodness of match
corr = 0.68   
area2 = 0.236 # large area mismatch threshold
area3 = 0.18  # small area mismatch threshold
