# from https://docs.github.com/en/actions/guides/publishing-docker-images

name: Build and PushContainer
on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*.*.*'
  pull_request:  
    branches:
      - 'main'

env:
  REGISTRY: hub.docker.com
  IMAGE_NAME: brownccv/icefloetracker-julia

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          username: ccvbot
          password: ${{ secrets.CCVBOT_DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}