# from https://docs.github.com/en/actions/guides/publishing-docker-images

name: Build and PushContainer - Julia
on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*.*.*'
  pull_request:
  workflow_dispatch:

env:
  REGISTRY: hub.docker.com
  IMAGE_NAME: brownccv/icefloetracker-julia
  TEST_TAG: brownccv/icefloetracker-julia:test

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          username: ccvbot
          password: ${{ secrets.CCVBOT_DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME }}
      
      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64
          load: true
          tags: ${{ env.TEST_TAG }}
      
      - name: Test CLI
        working-directory: ./script
        run: IFT="docker run -v `pwd`:/app -w /app --rm ${{ env.TEST_TAG }}" ./test-IFTPIpeline.jl-cli.sh
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}