# from https://docs.github.com/en/actions/guides/publishing-docker-images

name: Build Container - SOIT
on:
  push:
    branches:
      - main
    tags: '*'
  pull_request:
  release:
    types: [published]

env:
  REGISTRY: hub.docker.com
  IMAGE_NAME: brownccv/icefloetracker-soit
  TEST_TAG: brownccv/icefloetracker-soit:test

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Docker
        uses: docker/setup-docker-action@v4
        with:
          daemon-config: |
            {
              "debug": true,
              "features": {
                "containerd-snapshotter": true
              }
            }

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.IMAGE_NAME }}
            ghcr.io/${{ github.repository }}/soit

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./satellite-overpass-identification-tool
          platforms: linux/amd64,linux/arm64
          load: true
          tags: ${{ env.TEST_TAG }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          outputs: type=image,dest=${{ runner.temp }}/soit-image.tar
          
      - name: Upload Docker image artifact
        uses: actions/upload-artifact@v4
        with:
          name: soit-image
          path: ${{ runner.temp }}/soit-image.tar

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: soit-image
          path: ${{ runner.temp }}

      
      - name: Set up Docker
        uses: docker/setup-docker-action@v4
        with:
          daemon-config: |
            {
              "debug": true,
              "features": {
                "containerd-snapshotter": true
              }
            }

      - name: Load image
        run: |
          docker load --input ${{ runner.temp }}/soit-image.tar
          docker image ls -a
  
      
      - name: Test SOIT
        run: |
          docker run -v `pwd`:/app -w /app --rm ${{ env.TEST_TAG }} \
          -u ${{ secrets.SPACEUSER }} -p ${{ secrets.SPACEPSWD }} \
          --startdate 2013-03-31 --enddate 2013-05-01 \
          --lat 76.0015 --lon -18.4315 \
          --csvoutpath .
