name: Test SOIT

on:
    push:
        branches:
            - main
    pull_request:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Run SOIT with a directory
              run: |
                pipx run --spec ./satellite-overpass-identification-tool soit \
                --SPACEUSER ${{ secrets.SPACEUSER }} --SPACEPSWD ${{ secrets.SPACEPSWD }} \
                --startdate 2013-03-31 --enddate 2013-05-01 \
                --lat 76.0015 --lon -18.4315 \
                --csvoutpath .

            - name: Run SOIT with a particular path
              run: |
                pipx run --spec ./satellite-overpass-identification-tool soit \
                --SPACEUSER ${{ secrets.SPACEUSER }} --SPACEPSWD ${{ secrets.SPACEPSWD }} \
                --startdate 2013-03-31 --enddate 2013-05-01 \
                --lat 76.0015 --lon -18.4315 \
                --csvoutpath tracker-results.csv
            